"""Service for loading, saving, and validating emClarity parameter files.

Parameter files are MATLAB-style .m files with key-value pairs that
control every aspect of the cryo-EM processing pipeline.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from backend.models.parameter import (
    ParameterCategory,
    ParameterDefinition,
    ParameterFile,
    ParameterType,
    ParameterValidationResult,
    ParameterValue,
)

# Path to the parameter schema JSON generated from BH_parseParameterFile.m
_SCHEMA_PATH = Path(__file__).parent.parent.parent / "autonomous-build" / "templates" / "phase0-artifacts" / "parameter_schema.json"


class ParameterService:
    """Handles parameter schema, file I/O, and validation."""

    def __init__(self) -> None:
        self._schema: list[ParameterDefinition] | None = None

    def get_schema(self) -> list[ParameterDefinition]:
        """Return the parameter schema, loading from disk on first call.

        If the schema JSON file is not found, returns a minimal built-in
        set of core parameters so the backend remains functional.
        """
        if self._schema is not None:
            return self._schema

        if _SCHEMA_PATH.exists():
            self._schema = self._load_schema_from_json(_SCHEMA_PATH)
        else:
            self._schema = self._builtin_schema()

        return self._schema

    def load_parameter_file(self, path: str) -> ParameterFile:
        """Parse a MATLAB-style parameter file into structured data.

        Lines are expected in the format:
            paramName = value
        Comment lines starting with '%' are ignored.
        """
        file_path = Path(path)
        if not file_path.exists():
            raise FileNotFoundError(f"Parameter file not found: {path}")

        parameters: list[ParameterValue] = []
        content = file_path.read_text()

        for line in content.splitlines():
            line = line.strip()
            # Skip empty lines and MATLAB comments
            if not line or line.startswith("%"):
                continue

            match = re.match(r"^(\w+)\s*=\s*(.+?)(?:;?\s*(?:%.*)?)?$", line)
            if match:
                name = match.group(1)
                raw_value = match.group(2).strip().rstrip(";")
                value = self._parse_value(raw_value)
                parameters.append(ParameterValue(name=name, value=value))

        return ParameterFile(parameters=parameters, path=path)

    def save_parameter_file(self, param_file: ParameterFile) -> None:
        """Write parameter values to a MATLAB-style .m file atomically.

        Uses :func:`atomic_write` (temp file + ``os.replace()``) to
        prevent partial writes from corrupting the parameter file on disk.
        """
        from backend.utils.safe_json import atomic_write as _atomic_write_json
        import os as _os
        from pathlib import Path as _Path

        file_path = Path(param_file.path)
        file_path.parent.mkdir(parents=True, exist_ok=True)

        lines: list[str] = []
        lines.append("% emClarity parameter file")
        lines.append("% Generated by emClarity backend")
        lines.append("")

        for pv in param_file.parameters:
            value_str = self._format_value(pv.value)
            lines.append(f"{pv.name} = {value_str};")

        content = "\n".join(lines) + "\n"

        # Atomic write: write to temp file then os.replace()
        tmp = file_path.with_suffix(".tmp")
        try:
            tmp.write_text(content)
            _os.replace(tmp, file_path)
        except Exception:
            try:
                tmp.unlink(missing_ok=True)
            except OSError:
                pass
            raise

    def validate_parameters(
        self, parameters: list[ParameterValue]
    ) -> ParameterValidationResult:
        """Validate parameter values against the schema."""
        schema = self.get_schema()
        schema_map = {d.name: d for d in schema}

        errors: list[str] = []
        warnings: list[str] = []

        # Check required parameters
        provided_names = {p.name for p in parameters}
        for defn in schema:
            if defn.required and defn.name not in provided_names:
                errors.append(f"Required parameter '{defn.name}' is missing")

        # Validate each provided value
        for pv in parameters:
            defn = schema_map.get(pv.name)
            if defn is None:
                warnings.append(f"Unknown parameter '{pv.name}' - not in schema")
                continue

            # Range check for numeric types
            if defn.range is not None and isinstance(pv.value, (int, float)):
                lo, hi = defn.range
                if not (lo <= pv.value <= hi):
                    errors.append(
                        f"Parameter '{pv.name}' value {pv.value} "
                        f"outside allowed range [{lo}, {hi}]"
                    )

            # Enum / allowed-values check
            if defn.allowed_values is not None:
                # Compare both the raw value and its string representation
                # to handle mixed-type allowed_values lists from the schema
                if pv.value not in defn.allowed_values and str(pv.value) not in [
                    str(v) for v in defn.allowed_values
                ]:
                    errors.append(
                        f"Parameter '{pv.name}' value '{pv.value}' "
                        f"not in allowed values: {defn.allowed_values}"
                    )

        return ParameterValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings,
        )

    def load_parameter_file_v1(self, path: str) -> ParameterFile:
        """Parse a MATLAB-style parameter file with deprecated name migration.

        This is the preferred v1 method.  After parsing the raw key-value
        pairs, any deprecated parameter names (e.g. ``flgCCCcutoff``) are
        transparently translated to their current canonical names before the
        result is returned.

        Args:
            path: Filesystem path to the ``.m`` parameter file.

        Returns:
            A :class:`ParameterFile` whose parameter names have been migrated
            to their canonical forms.

        Raises:
            FileNotFoundError: When the file does not exist.
        """
        param_file = self.load_parameter_file(path)
        migrated = self._migrate_deprecated_names(param_file.parameters)
        return ParameterFile(parameters=migrated, path=path)

    def _migrate_deprecated_names(
        self, parameters: list[ParameterValue]
    ) -> list[ParameterValue]:
        """Translate any deprecated parameter names to their canonical form.

        Reads the ``deprecated_name`` field from the golden schema to build a
        lookup table, then replaces deprecated names in the supplied list.
        Parameters whose names are already canonical are returned unchanged.
        """
        deprecated_lookup: dict[str, str] = {}
        if _SCHEMA_PATH.exists():
            raw = json.loads(_SCHEMA_PATH.read_text())
            entries = raw if isinstance(raw, list) else raw.get("parameters", [])
            for entry in entries:
                dep = entry.get("deprecated_name")
                if dep:
                    deprecated_lookup[dep] = entry["name"]

        migrated: list[ParameterValue] = []
        for pv in parameters:
            canonical = deprecated_lookup.get(pv.name, pv.name)
            migrated.append(ParameterValue(name=canonical, value=pv.value))
        return migrated

    def validate_parameters_dict(
        self, parameters: dict[str, Any]
    ) -> ParameterValidationResult:
        """Validate a flat dict of ``{name: value}`` pairs against the schema.

        This is the preferred method for the v1 API endpoint.  It handles:
        - Deprecated parameter name translation (e.g. ``flgCCCcutoff`` ->
          ``ccc_cutoff``) so that legacy parameter files are accepted.
        - Type checking: numeric parameters reject non-numeric strings.
        - Range validation and required-parameter checks.

        Args:
            parameters: Dict mapping parameter names (or deprecated names)
                to their values.

        Returns:
            A ParameterValidationResult with ``valid=True`` when all checks
            pass, otherwise with ``errors`` populated.
        """
        schema = self.get_schema()
        schema_map = {d.name: d for d in schema}

        # Build deprecated-name -> current-name lookup from the schema JSON.
        deprecated_lookup: dict[str, str] = {}
        if _SCHEMA_PATH.exists():
            raw = json.loads(_SCHEMA_PATH.read_text())
            entries = raw if isinstance(raw, list) else raw.get("parameters", [])
            for entry in entries:
                dep = entry.get("deprecated_name")
                if dep:
                    deprecated_lookup[dep] = entry["name"]

        errors: list[str] = []
        warnings: list[str] = []

        # Translate deprecated names and build a normalised working dict.
        normalised: dict[str, Any] = {}
        for name, value in parameters.items():
            canonical = deprecated_lookup.get(name, name)
            normalised[canonical] = value

        # Check required parameters.
        for defn in schema:
            if defn.required and defn.name not in normalised:
                errors.append(f"Required parameter '{defn.name}' is missing")

        # Numeric types that require a numeric value.
        numeric_types = {ParameterType.NUMERIC, ParameterType.FLOAT, ParameterType.INTEGER}

        # Validate each provided value.
        for name, value in normalised.items():
            defn = schema_map.get(name)
            if defn is None:
                warnings.append(f"Unknown parameter '{name}' - not in schema")
                continue

            # Type check: numeric parameters must not be non-numeric strings.
            if defn.type in numeric_types and isinstance(value, str):
                try:
                    float(value)
                except (ValueError, TypeError):
                    errors.append(
                        f"Parameter '{name}' expects a numeric value, "
                        f"got string '{value}'"
                    )
                    continue  # skip further checks for this parameter

            # Range check for numeric types.
            if defn.range is not None and isinstance(value, (int, float)):
                lo, hi = defn.range
                if not (lo <= value <= hi):
                    errors.append(
                        f"Parameter '{name}' value {value} "
                        f"outside allowed range [{lo}, {hi}]"
                    )

            # Enum / allowed-values check.
            if defn.allowed_values is not None:
                if value not in defn.allowed_values and str(value) not in [
                    str(v) for v in defn.allowed_values
                ]:
                    errors.append(
                        f"Parameter '{name}' value '{value}' "
                        f"not in allowed values: {defn.allowed_values}"
                    )

        return ParameterValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_value(raw: str) -> Any:
        """Convert a raw MATLAB value string to a Python type."""
        stripped = raw.strip().strip("'\"")

        # Boolean
        if stripped.lower() in ("true", "1") and stripped.lower() in ("true",):
            return True
        if stripped.lower() in ("false", "0") and stripped.lower() in ("false",):
            return False

        # Vector: [1, 2, 3]
        if stripped.startswith("[") and stripped.endswith("]"):
            inner = stripped[1:-1]
            parts = re.split(r"[,\s]+", inner.strip())
            try:
                return [float(p) if "." in p else int(p) for p in parts if p]
            except ValueError:
                return stripped

        # Numeric
        try:
            if "." in stripped:
                return float(stripped)
            return int(stripped)
        except ValueError:
            pass

        return stripped

    @staticmethod
    def _format_value(value: Any) -> str:
        """Format a Python value for writing to a MATLAB parameter file."""
        if isinstance(value, bool):
            return "1" if value else "0"
        if isinstance(value, list):
            parts = ", ".join(str(v) for v in value)
            return f"[{parts}]"
        if isinstance(value, str):
            return f"'{value}'"
        return str(value)

    @staticmethod
    def _load_schema_from_json(path: Path) -> list[ParameterDefinition]:
        """Load parameter definitions from the generated JSON schema."""
        data = json.loads(path.read_text())

        definitions: list[ParameterDefinition] = []
        params = data if isinstance(data, list) else data.get("parameters", [])

        for entry in params:
            # Map JSON fields to our model, with sensible defaults.
            # The golden schema uses: numeric, numeric_array, string, boolean.
            param_type = entry.get("type", "string")
            type_map = {
                "string": ParameterType.STRING,
                "integer": ParameterType.INTEGER,
                "float": ParameterType.FLOAT,
                "number": ParameterType.FLOAT,
                "boolean": ParameterType.BOOLEAN,
                "vector": ParameterType.VECTOR,
                "enum": ParameterType.ENUM,
                "numeric": ParameterType.NUMERIC,
                "numeric_array": ParameterType.NUMERIC_ARRAY,
            }

            category_str = entry.get("category", "general")
            try:
                category = ParameterCategory(category_str)
            except ValueError:
                category = ParameterCategory.GENERAL

            definitions.append(
                ParameterDefinition(
                    name=entry["name"],
                    type=type_map.get(param_type, ParameterType.STRING),
                    required=entry.get("required", False),
                    default=entry.get("default"),
                    range=entry.get("range"),
                    allowed_values=entry.get("allowed_values"),
                    description=entry.get("description", ""),
                    category=category,
                    units=entry.get("units"),
                )
            )

        return definitions

    @staticmethod
    def _builtin_schema() -> list[ParameterDefinition]:
        """Return a minimal built-in schema for core parameters.

        Used as a fallback when the full JSON schema file is not available.
        """
        return [
            ParameterDefinition(
                name="PIXEL_SIZE",
                type=ParameterType.FLOAT,
                required=True,
                description="Pixel size of the raw tilt-series images",
                category=ParameterCategory.GENERAL,
                units="angstroms",
                range=[0.1, 50.0],
            ),
            ParameterDefinition(
                name="SuperResolution",
                type=ParameterType.INTEGER,
                required=False,
                default=0,
                description="Super-resolution factor (0 = off, 1 = on)",
                category=ParameterCategory.GENERAL,
                range=[0, 1],
            ),
            ParameterDefinition(
                name="Ali_samplingRate",
                type=ParameterType.VECTOR,
                required=False,
                default=[4, 3, 2],
                description="Sampling rates for alignment cycles",
                category=ParameterCategory.ALIGNMENT,
            ),
            ParameterDefinition(
                name="Cls_className",
                type=ParameterType.STRING,
                required=False,
                default="",
                description="Class name for classification",
                category=ParameterCategory.CLASSIFICATION,
            ),
            ParameterDefinition(
                name="GPU",
                type=ParameterType.VECTOR,
                required=True,
                description="GPU device IDs to use",
                category=ParameterCategory.SYSTEM,
            ),
        ]
