function EMC_setup_synthetic_project(project_path, synthetic_data_path, particle_radius, particle_mass, varargin)
% EMC_setup_synthetic_project - Set up an emClarity project from synthetic data
%
% This function creates a complete emClarity project directory structure from
% synthetic data generated by EMC_syntheticTomogram and EMC_generate_synthetic_tltFile.
%
% Usage:
%   EMC_setup_synthetic_project(project_path, synthetic_data_path, particle_radius, particle_mass)
%   EMC_setup_synthetic_project(..., 'param', value, ...)
%
% Required Inputs:
%   project_path       - Full path to project directory (must not exist)
%   synthetic_data_path - Path to directory containing synthetic data files
%   particle_radius    - Particle radius in Angstroms (scalar or [x,y,z] vector)
%   particle_mass      - Particle mass in Megadaltons
%
% Required Files in synthetic_data_path:
%   *.tomosize - Tomogram size file (4 lines: x, y, z dimensions, pixel size in Angstroms)
%   *.csv      - Particle coordinates (31-field format from EMC_syntheticTomogram)
%   *_ctf.tlt  - Tilt geometry file (23-column format)
%   *.st       - Projected tilt series
%
% Optional Parameters (name-value pairs):
%   'dose_scale'         - Scale factor for Poisson noise (default: 0)
%                          Applied as: poissrnd(pixel_value * exposure * dose_scale)
%                          where exposure is per-projection dose from TLT file
%                          >1 increases SNR, <1 decreases SNR
%                          =0 skips noise entirely and symlinks the original file
%   'gpu'                - GPU device ID (default: 1). Set to 0 for CPU-only.
%   'st_suffix'          - Suffix in source .st filenames (default: '')
%                          e.g., '_dose_scale_5' matches '*_dose_scale_5.st'
%                          The suffix is stripped when copying to fixedStacks/
%   'link_aliStacks'     - Create symlinks in aliStacks/ (default: false)
%   'nGPUs'              - Number of GPUs (default: 1)
%   'nCpuCores'          - Number of CPU cores (default: 1)
%   'symmetry'           - Point group symmetry (default: 'C1')
%   'Cs_mm'              - Spherical aberration in mm (default: 2.7)
%   'voltage_kev'        - Accelerating voltage in keV (default: 300)
%   'amplitude_contrast' - Amplitude contrast fraction (default: 0.07)
%   'Ali_mType'          - Alignment mask type: 'sphere' or 'cylinder' (default: 'sphere')
%   'Cls_mType'          - Classification mask type: 'sphere' or 'cylinder' (default: 'sphere')
%
% Output:
%   Creates project directory with:
%   - fixedStacks/      : .st files with Poisson noise applied
%   - fixedStacks/ctf/  : Symlinks to .tlt files with proper naming
%   - aliStacks/        : Directory created (symlinks only if link_aliStacks=true)
%   - recon/            : Tomogram coordinate files
%   - convmap/          : Particle coordinate CSVs (6-column format)
%   - cache/            : Temporary file directory
%   - logFile/          : Log directory
%   - param0.m          : Parameter file for emClarity init
%
% Example:
%   EMC_setup_synthetic_project('/projects/my_synth', '/data/synthetic', 80, ...
%                               'symmetry', 'C12', 'nGPUs', 2)

%% Parse input parameters
p = inputParser;
addRequired(p, 'project_path', @ischar);
addRequired(p, 'synthetic_data_path', @ischar);
addRequired(p, 'particle_radius', @isnumeric);
addRequired(p, 'particle_mass', @isnumeric);

% Optional parameters
addParameter(p, 'dose_scale', 0, @isnumeric);
addParameter(p, 'gpu', 1, @isnumeric);
addParameter(p, 'st_suffix', '', @ischar);
addParameter(p, 'link_aliStacks', false, @islogical);
addParameter(p, 'nGPUs', 1, @isnumeric);
addParameter(p, 'nCpuCores', 1, @isnumeric);
addParameter(p, 'symmetry', 'C1', @ischar);
addParameter(p, 'Cs_mm', 2.7, @isnumeric);
addParameter(p, 'voltage_kev', 300, @isnumeric);
addParameter(p, 'amplitude_contrast', 0.07, @isnumeric);
addParameter(p, 'Ali_mType', 'sphere', @ischar);
addParameter(p, 'Cls_mType', 'sphere', @ischar);

parse(p, project_path, synthetic_data_path, particle_radius, particle_mass, varargin{:});
opts = p.Results;

% Convert scalar particle_radius to [x,y,z] vector
if isscalar(particle_radius)
    particle_radius = [particle_radius, particle_radius, particle_radius];
end

%% Step 1: Input Validation
fprintf('=== EMC_setup_synthetic_project ===\n\n');

% REVERT
% Check project path does not exist
%if exist(project_path, 'dir')
%    error('EMC_setup_synthetic_project:ProjectExists', ...
%          'Project directory already exists: %s', project_path);
%end

% Check synthetic data path exists
if ~exist(synthetic_data_path, 'dir')
    error('EMC_setup_synthetic_project:DataNotFound', ...
          'Synthetic data directory not found: %s', synthetic_data_path);
end

% Find all required file types
tomosize_files = dir(fullfile(synthetic_data_path, '*.tomosize'));
csv_files = dir(fullfile(synthetic_data_path, '*.csv'));
tlt_files = dir(fullfile(synthetic_data_path, '*_ctf.tlt'));
st_pattern = sprintf('*%s.st', opts.st_suffix);
st_files = dir(fullfile(synthetic_data_path, st_pattern));

fprintf('Found synthetic data files:\n');
fprintf('  .tomosize files: %d\n', length(tomosize_files));
fprintf('  .csv files: %d\n', length(csv_files));
fprintf('  .tlt files: %d\n', length(tlt_files));
fprintf('  .st files (%s):  %d\n', st_pattern, length(st_files));

% Validate all 4 file types are present
if isempty(tomosize_files)
    error('EMC_setup_synthetic_project:MissingFiles', ...
          'No .tomosize files found in %s', synthetic_data_path);
end
if isempty(csv_files)
    error('EMC_setup_synthetic_project:MissingFiles', ...
          'No .csv files found in %s', synthetic_data_path);
end
if isempty(tlt_files)
    error('EMC_setup_synthetic_project:MissingFiles', ...
          'No *_ctf.tlt files found in %s', synthetic_data_path);
end
if isempty(st_files)
    error('EMC_setup_synthetic_project:MissingFiles', ...
          'No .st files found in %s', synthetic_data_path);
end

% For now, validate 1:1 correspondence (same count for all file types)
if length(tomosize_files) ~= length(csv_files)
    error('EMC_setup_synthetic_project:FileMismatch', ...
          'Number of .tomosize files (%d) does not match .csv files (%d)', ...
          length(tomosize_files), length(csv_files));
end
if length(tomosize_files) ~= length(tlt_files)
    error('EMC_setup_synthetic_project:FileMismatch', ...
          'Number of .tomosize files (%d) does not match .tlt files (%d)', ...
          length(tomosize_files), length(tlt_files));
end
if length(tomosize_files) ~= length(st_files)
    error('EMC_setup_synthetic_project:FileMismatch', ...
          'Number of .tomosize files (%d) does not match .st files (%d)', ...
          length(tomosize_files), length(st_files));
end

n_tomos = length(tomosize_files);
fprintf('\nProcessing %d synthetic tomogram(s)\n\n', n_tomos);

%% Step 2: Pixel Size Validation
fprintf('Validating pixel sizes...\n');

% Read pixel size from TLT file (column 16, in meters)
tlt_path = fullfile(synthetic_data_path, tlt_files(1).name);
tlt_data = load(tlt_path);
pixel_size_m = tlt_data(1, 16);  % Column 16 is pixel size in meters
pixel_size_angstrom = pixel_size_m * 1e10;

fprintf('  Pixel size from TLT: %.4f Angstroms\n', pixel_size_angstrom);

% Read and validate .tomosize files
% Format: 4 lines - x, y, z dimensions, then pixel size (Angstroms)
tomo_dimensions = zeros(n_tomos, 3);  % Store dimensions for later use
for i = 1:n_tomos
    tomosize_path = fullfile(synthetic_data_path, tomosize_files(i).name);
    fid = fopen(tomosize_path, 'r');
    if fid == -1
        error('EMC_setup_synthetic_project:FileReadError', ...
              'Could not open .tomosize file: %s', tomosize_path);
    end
    tomo_dimensions(i, 1) = str2double(fgetl(fid));  % x
    tomo_dimensions(i, 2) = str2double(fgetl(fid));  % y
    tomo_dimensions(i, 3) = str2double(fgetl(fid));  % z
    tomosize_pixel = str2double(fgetl(fid));         % pixel size
    fclose(fid);

    % Validate pixel size matches TLT
    diff_percent = abs(tomosize_pixel - pixel_size_angstrom) / pixel_size_angstrom * 100;
    if diff_percent > 1.0  % Allow 1% tolerance
        error('EMC_setup_synthetic_project:PixelSizeMismatch', ...
              'Pixel size mismatch for %s: tomosize=%.4f, TLT=%.4f Angstroms', ...
              tomosize_files(i).name, tomosize_pixel, pixel_size_angstrom);
    end
end
fprintf('  All pixel sizes validated.\n\n');

%% Step 2b: Calculate Mean Defocus from TLT Files
fprintf('Calculating defocus statistics...\n');
all_defocus = [];
for i = 1:n_tomos
    tlt_path = fullfile(synthetic_data_path, tlt_files(i).name);
    tlt_data = load(tlt_path);
    defocus_values = tlt_data(:, 15);  % Column 15 is defocus in meters
    all_defocus = [all_defocus; defocus_values];
end
mean_defocus = mean(all_defocus);
% defWindow is +/-50% of mean defocus, but minimum 300nm (3e-7 meters)
def_window = max(0.5 * mean_defocus, 3e-7);
fprintf('  Mean defocus: %.2f um\n', mean_defocus * 1e6);
fprintf('  Defocus window: %.2f um\n', def_window * 1e6);

%% Step 3: Create Directory Structure
fprintf('Creating project directory structure...\n');

mkdir(project_path);
mkdir(fullfile(project_path, 'fixedStacks'));
mkdir(fullfile(project_path, 'fixedStacks', 'ctf'));
mkdir(fullfile(project_path, 'aliStacks'));
mkdir(fullfile(project_path, 'recon'));
mkdir(fullfile(project_path, 'convmap'));
mkdir(fullfile(project_path, 'cache'));
mkdir(fullfile(project_path, 'logFile'));

fprintf('  Created: %s\n', project_path);
fprintf('  Created: fixedStacks/, fixedStacks/ctf/, aliStacks/\n');
fprintf('  Created: recon/, convmap/, cache/, logFile/\n\n');

%% Initialize GPU if requested
if opts.gpu > 0
    gpuDevice(opts.gpu);
    fprintf('Using GPU device %d for noise generation\n\n', opts.gpu);
end

%% Process each tomogram
for i = 1:n_tomos
    % Derive tiltName from the .st filename (strip extension and suffix)
    [~, st_basename, ~] = fileparts(st_files(i).name);
    % Strip the st_suffix to get the base tilt_name
    if ~isempty(opts.st_suffix) && endsWith(st_basename, opts.st_suffix)
        tilt_name = st_basename(1:end-length(opts.st_suffix));
    else
        tilt_name = st_basename;
    end

    fprintf('Processing tomogram %d: %s (from %s)\n', i, tilt_name, st_files(i).name);

    %% Step 4: Process Tilt Series (.st files) - Apply Poisson noise or symlink
    st_source = fullfile(synthetic_data_path, st_files(i).name);
    % Destination uses tilt_name without suffix
    st_dest_fixed = fullfile(project_path, 'fixedStacks', [tilt_name '.fixed']);

    % Load TLT file for this tomogram (needed for exposure and later steps)
    tlt_full_path = fullfile(synthetic_data_path, tlt_files(i).name);
    tlt_data = load(tlt_full_path);

    if opts.dose_scale == 0
        % Skip noise - create symlink to original
        system(sprintf('ln -s "%s" "%s"', st_source, st_dest_fixed));
        fprintf('  Linked .st to fixedStacks/ (no noise)\n');
    else
        % Read the tilt series stack
        st_stack = OPEN_IMG('single', st_source);
        % Assert no negative values (required for Poisson)
        assert(all(st_stack(:) >= 0), ...
               'EMC_setup_synthetic_project:NegativeValues', ...
               'Tilt series %s contains negative values, cannot apply Poisson noise', ...
               st_files(i).name);

        exposure_per_proj = EMC_tlt_get_projection_values(tlt_data, 'exposure');
        n_projections = size(st_stack, 3);

        fprintf('  Applying Poisson noise (dose_scale=%.2f, %d projections)\n', ...
                opts.dose_scale, n_projections);

        % Apply Poisson noise with per-projection dose scaling
        if opts.gpu > 0
            st_stack_gpu = gpuArray(st_stack);
        end
        for j = 1:n_projections
            st_stack_gpu(:,:,j) = poissrnd(st_stack_gpu(:,:,j) .* exposure_per_proj(j) .* opts.dose_scale);
        end
        st_stack = gather(st_stack_gpu);

        % Get pixel size for saving
        mrc_obj = MRCImage(st_source, 0);
        st_header = getHeader(mrc_obj);
        st_pixel_size = st_header.cellDimensionX / st_header.nX;

        % Save noisy stack to fixedStacks/
        SAVE_IMG(st_stack, st_dest_fixed, st_pixel_size);
        fprintf('  Saved noisy .st to fixedStacks/\n');
    end

    % Optionally link to aliStacks
    if opts.link_aliStacks
        st_dest_ali = fullfile(project_path, 'aliStacks', sprintf('%s_ali1.st', tilt_name));
        system(sprintf('ln -s "%s" "%s"', st_dest_fixed, st_dest_ali));
        fprintf('  Linked .st to aliStacks/\n');
    end

    %% Step 5: Link TLT Files with Correct Naming
    tlt_source = fullfile(synthetic_data_path, tlt_files(i).name);
    tlt_dest = fullfile(project_path, 'fixedStacks', 'ctf', sprintf('%s_ali1_ctf.tlt', tilt_name));

    system(sprintf('ln -s "%s" "%s"', tlt_source, tlt_dest));
    fprintf('  Linked .tlt to fixedStacks/ctf/%s_ali1_ctf.tlt\n', tilt_name);

    %% Step 5b: Generate .tlt and .xf files in fixedStacks/
    % Use helper function to get values sorted by projection index
    % (tlt_data already loaded above for exposure calculation)
    tilt_angles_sorted = EMC_tlt_get_projection_values(tlt_data, 4);
    shift_x_sorted = EMC_tlt_get_projection_values(tlt_data, 2);
    shift_y_sorted = EMC_tlt_get_projection_values(tlt_data, 3);

    % Write .tlt file (just tilt angles, one per line)
    tlt_angles_dest = fullfile(project_path, 'fixedStacks', sprintf('%s.tlt', tilt_name));
    fid = fopen(tlt_angles_dest, 'w');
    for j = 1:length(tilt_angles_sorted)
        fprintf(fid, '%.3f\n', tilt_angles_sorted(j));
    end
    fclose(fid);
    fprintf('  Created fixedStacks/%s.tlt\n', tilt_name);

    % Write .xf file (A11 A12 A21 A22 dX dY - identity rotation with shifts)
    xf_dest = fullfile(project_path, 'fixedStacks', sprintf('%s.xf', tilt_name));
    fid = fopen(xf_dest, 'w');
    for j = 1:length(tilt_angles_sorted)
        % Identity rotation matrix [1 0; 0 1] with shifts from TLT
        fprintf(fid, '%f %f %f %f %f %f\n', 1.0, 0.0, 0.0, 1.0, ...
                shift_x_sorted(j), shift_y_sorted(j));
    end
    fclose(fid);
    fprintf('  Created fixedStacks/%s.xf\n', tilt_name);

    %% Step 6: Convert and Create convmap CSV Files
    csv_source = fullfile(synthetic_data_path, csv_files(i).name);
    csv_data = load(csv_source);  % Load 31-column CSV

    % Extract columns 11-16: posX, posY, posZ, phi, theta, psi-phi
    if size(csv_data, 2) >= 16
        csv_6col = csv_data(:, 11:16);
    else
        error('EMC_setup_synthetic_project:InvalidCSV', ...
              'CSV file %s has only %d columns (expected at least 16)', ...
              csv_files(i).name, size(csv_data, 2));
    end

    % Write 6-column CSV to convmap/<tiltName>_1.csv
    convmap_dest = fullfile(project_path, 'convmap', sprintf('%s_1.csv', tilt_name));

    fid = fopen(convmap_dest, 'w');
    for j = 1:size(csv_6col, 1)
        fprintf(fid, '%f %f %f %f %f %f\n', csv_6col(j, :));
    end
    fclose(fid);

    fprintf('  Created convmap/%s_1.csv (%d particles)\n', tilt_name, size(csv_6col, 1));

    %% Step 7: Create recon/*.coords Files
    % Use tomogram dimensions from .tomosize file (stored earlier)
    nx = tomo_dimensions(i, 1);
    ny = tomo_dimensions(i, 2);
    nz = tomo_dimensions(i, 3);

    % Create coords file
    coords_dest = fullfile(project_path, 'recon', sprintf('%s_recon.coords', tilt_name));

    fid = fopen(coords_dest, 'w');
    fprintf(fid, '%s\n', tilt_name);  % Line 1: tiltName
    fprintf(fid, '1\n');               % Line 2: nTomos (1 for now)
    % 6 values for the tomogram: NX, NY, NZ, dX, dY, dZ
    fprintf(fid, '%d\n', nx);
    fprintf(fid, '%d\n', ny);
    fprintf(fid, '%d\n', nz);
    fprintf(fid, '0\n');               % dX (centered)
    fprintf(fid, '0\n');               % dY (centered)
    fprintf(fid, '0\n');               % dZ (centered)
    fclose(fid);

    fprintf('  Created recon/%s_recon.coords (dims: %dx%dx%d)\n', tilt_name, nx, ny, nz);
end

%% Step 8: Create Parameter File
fprintf('\nCreating parameter file...\n');

[~, project_name, ~] = fileparts(project_path);

param_path = fullfile(project_path, 'param0.m');
fid = fopen(param_path, 'w');

fprintf(fid, '%% emClarity parameter file for synthetic project: %s\n', project_name);
fprintf(fid, '%% Generated by EMC_setup_synthetic_project\n');
fprintf(fid, '%% Date: %s\n\n', datestr(now, 'yyyy-mm-dd HH:MM:SS'));

% Section 1: Basic Config
fprintf(fid, 'subTomoMeta=%s\n', project_name);
fprintf(fid, 'fastScratchDisk=ram\n');
fprintf(fid, 'nGPUs=%d\n', opts.nGPUs);
fprintf(fid, 'nCpuCores=%d\n', opts.nCpuCores);
fprintf(fid, 'n_tilt_workers=4\n\n');

% Section 2: Processing Flags
fprintf(fid, 'phakePhasePlate=0\n');
fprintf(fid, 'flgQualityWeight=0\n');
fprintf(fid, 'flgMultiRefAlignment=0\n');
fprintf(fid, 'updateClassByBestReferenceScore=0\n');
fprintf(fid, 'max_ctf3dDepth=100e-9\n');
fprintf(fid, 'whitenPS=[0,0,0.5]\n');
fprintf(fid, 'diameter_fraction_for_local_stats=0.9\n');
fprintf(fid, 'test_local=1\n');
fprintf(fid, 'scale_mip=0\n');
fprintf(fid, 'nPeaks=1\n');
fprintf(fid, 'symmetry=%s\n', opts.symmetry);
fprintf(fid, 'doHelical=0\n');
fprintf(fid, 'Pca_refineKmeans=1\n\n');

% Section 3: Mask Parameters
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%    Mask parameters    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'particleRadius=[%d,%d,%d]\n', ...
        particle_radius(1), particle_radius(2), particle_radius(3));
fprintf(fid, 'particleMass=%.2f\n', particle_mass);
fprintf(fid, 'Ali_mType=%s\n', opts.Ali_mType);
fprintf(fid, 'Cls_mType=%s\n', opts.Cls_mType);
fprintf(fid, 'Peak_mType=sphere\n');
fprintf(fid, 'Peak_mRadius=[%d,%d,%d]\n', ...
        particle_radius(1), particle_radius(2), particle_radius(3));
% Ali/Cls mask radius ~1.2x particle radius
ali_radius = round(particle_radius * 1.2);
fprintf(fid, 'Ali_mRadius=[%d,%d,%d]\n', ali_radius(1), ali_radius(2), ali_radius(3));
fprintf(fid, 'Ali_mCenter=[0,0,0]\n');
fprintf(fid, 'Cls_mRadius=[%d,%d,%d]\n', ali_radius(1), ali_radius(2), ali_radius(3));
fprintf(fid, 'Cls_mCenter=[0,0,0]\n');
fprintf(fid, 'Ali_samplingRate=1\n');
fprintf(fid, 'Cls_samplingRate=1\n');
fprintf(fid, 'move_reference_by_com=0\n\n');

% Section 4: TomoCPR Parameters
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%    Tomo-constrained projection refinement parameters    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'tomoCprDefocusRefine=0\n');
fprintf(fid, 'tomoCprDefocusRange=500e-9\n');
fprintf(fid, 'tomoCprDefocusStep=20e-9\n');
fprintf(fid, 'tomoCPR_target_n_patches_x_y=[3,4]\n');
fprintf(fid, 'tomoCPR_random_subset=400\n\n');

% Section 5: Alignment Parameters
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    subTomogram alignment    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'Raw_className=0\n');
fprintf(fid, 'Raw_classes_odd=[0;1]\n');
fprintf(fid, 'Raw_classes_eve=[0;1]\n');
fprintf(fid, 'symmetry_constrained_search=0\n');
fprintf(fid, 'Raw_angleSearch=[3,1,3,0.75]\n');
fprintf(fid, 'print_alignment_stats=1\n\n');

% Section 6: Template Matching
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    Template matching parameters    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'Tmp_bandpass=[0.01,1200,25]\n');
fprintf(fid, 'Tmp_samplingRate=5\n');
fprintf(fid, 'Tmp_threshold=1500\n');
fprintf(fid, 'Tmp_angleSearch=[180,12,180,12]\n');
fprintf(fid, 'Tmp_targetSize=[512,512,768]\n');
fprintf(fid, 'Tmp_half_precision=0\n\n');

% Section 7: Classification/FSC
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    FSC Parameters    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'flgCones=0\n');
fprintf(fid, 'fsc_shape_mask=1\n');
fprintf(fid, 'Fsc_bfactor=10\n');
fprintf(fid, 'fscGoldSplitOnTomos=0\n');
fprintf(fid, 'fscWithChimera=0\n\n');

fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    Classification Parameters    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'Cls_className=1\n');
fprintf(fid, 'Cls_classes_odd=[1;1]\n');
fprintf(fid, 'Cls_classes_eve=[1;1]\n');
fprintf(fid, 'Pca_constrain_symmetry=1\n');
fprintf(fid, 'flgPcaShapeMask=0\n');
fprintf(fid, 'flgClassify=0\n');
fprintf(fid, 'Pca_clusters=[2,4]\n');
fprintf(fid, 'Pca_maxEigs=64\n');
fprintf(fid, 'pcaScaleSpace=[18,32,64]\n');
fprintf(fid, 'Pca_coeffs=[3:48;3:48;3:48;3:48]\n');
fprintf(fid, 'Pca_bandpass=[0.01,1200,18]\n');
fprintf(fid, 'PcaGpuPull=5000\n');
fprintf(fid, 'Pca_randSubset=0\n\n');

% Section 8: CTF/Microscope Parameters
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    CTF Parameters (meters, volts)    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'PIXEL_SIZE=%.6e\n', pixel_size_m);
fprintf(fid, 'SuperResolution=0\n');
fprintf(fid, 'Cs=%.6e\n', opts.Cs_mm * 1e-3);
fprintf(fid, 'VOLTAGE=%.6e\n', opts.voltage_kev * 1e3);
fprintf(fid, 'AMPCONT=%.4f\n', opts.amplitude_contrast);
fprintf(fid, 'defEstimate=%.6e\n', mean_defocus);
fprintf(fid, 'defWindow=%.6e\n', def_window);
fprintf(fid, 'defCutOff=6e-10\n');
fprintf(fid, 'CUM_e_DOSE=180\n');
fprintf(fid, 'beadDiameter=10e-9\n\n');

% Section 9: Dose Symmetric Settings
fprintf(fid, 'oneOverCosineDose=0\n');
fprintf(fid, 'startingAngle=0\n');
fprintf(fid, 'startingDirection=pos\n');
fprintf(fid, 'doseSymmetricIncrement=3\n');
fprintf(fid, 'doseAtMinTilt=3.0\n\n');

% Section 10: Advanced Parameters
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    Advanced Parameters    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'scaleCalcSize=1.5\n');
fprintf(fid, 'autoAli_min_sampling_rate=10\n');
fprintf(fid, 'autoAli_max_sampling_rate=4\n');
fprintf(fid, 'autoAli_patch_size_factor=4\n');
fprintf(fid, 'autoAli_patch_overlap=0.6\n');
fprintf(fid, 'autoAli_max_resolution=18\n');
fprintf(fid, 'autoAli_refine_on_beads=0\n');
fprintf(fid, 'autoAli_iterations_per_bin=2\n');
fprintf(fid, 'autoAli_patch_tracking_border=64\n');
fprintf(fid, 'autoAli_n_iters_no_rotation=2\n');
fprintf(fid, 'autoAli_max_shift_in_angstroms=300\n');
fprintf(fid, 'autoAli_max_shift_factor=1\n');
fprintf(fid, 'ctf_tile_overlap=4\n');
fprintf(fid, 'refine_defocus_cisTEM=0\n');
fprintf(fid, 'rerun_refinement_cisTEM=0\n');
fprintf(fid, 'cisTEM_invert_tilt_for_defocus_calc=0\n');
fprintf(fid, 'tmp_model_scale=1.0\n');
fprintf(fid, 'use_defocus_from_emc=false\n');
fprintf(fid, 'save_mapback_classes=1\n');
fprintf(fid, 'tomoCPR_n_particles_minimum=1\n');
fprintf(fid, 'measure_noise_variance=0\n');

fclose(fid);

fprintf('  Created param0.m\n');

%% Step 9: Validation Summary
fprintf('\n=== Project Setup Complete ===\n\n');
fprintf('Project directory: %s\n', project_path);
fprintf('Tomograms processed: %d\n', n_tomos);
fprintf('Pixel size: %.4f Angstroms\n', pixel_size_angstrom);
fprintf('Particle radius: [%d, %d, %d] Angstroms\n', ...
        particle_radius(1), particle_radius(2), particle_radius(3));
fprintf('\nNext step: cd to project directory and run:\n');
fprintf('  emClarity init param0.m zyz fwd\n\n');

end  % main function
