function EMC_setup_synthetic_project(project_path, synthetic_data_path, particle_radius, varargin)
% EMC_setup_synthetic_project - Set up an emClarity project from synthetic data
%
% This function creates a complete emClarity project directory structure from
% synthetic data generated by EMC_syntheticTomogram and EMC_generate_synthetic_tltFile.
%
% Usage:
%   EMC_setup_synthetic_project(project_path, synthetic_data_path, particle_radius)
%   EMC_setup_synthetic_project(..., 'param', value, ...)
%
% Required Inputs:
%   project_path       - Full path to project directory (must not exist)
%   synthetic_data_path - Path to directory containing synthetic data files
%   particle_radius    - Particle radius in Angstroms (scalar or [x,y,z] vector)
%
% Required Files in synthetic_data_path:
%   *.tomosize - Tomogram size file (4 lines: x, y, z dimensions, pixel size in Angstroms)
%   *.csv      - Particle coordinates (31-field format from EMC_syntheticTomogram)
%   *_ctf.tlt  - Tilt geometry file (23-column format)
%   *.st       - Projected tilt series
%
% Optional Parameters (name-value pairs):
%   'dose_scale'         - Scale factor for Poisson noise (default: 1.0)
%                          Applied as: poissrnd(pixel_value * dose_scale)
%                          >1 increases SNR, <1 decreases SNR
%   'link_aliStacks'     - Create symlinks in aliStacks/ (default: false)
%   'nGPUs'              - Number of GPUs (default: 1)
%   'nCpuCores'          - Number of CPU cores (default: 1)
%   'symmetry'           - Point group symmetry (default: 'C1')
%   'Cs_mm'              - Spherical aberration in mm (default: 2.7)
%   'voltage_kev'        - Accelerating voltage in keV (default: 300)
%   'amplitude_contrast' - Amplitude contrast fraction (default: 0.07)
%
% Output:
%   Creates project directory with:
%   - fixedStacks/      : .st files with Poisson noise applied
%   - fixedStacks/ctf/  : Symlinks to .tlt files with proper naming
%   - aliStacks/        : Directory created (symlinks only if link_aliStacks=true)
%   - recon/            : Tomogram coordinate files
%   - convmap/          : Particle coordinate CSVs (6-column format)
%   - cache/            : Temporary file directory
%   - logFile/          : Log directory
%   - param0.m          : Parameter file for emClarity init
%
% Example:
%   EMC_setup_synthetic_project('/projects/my_synth', '/data/synthetic', 80, ...
%                               'symmetry', 'C12', 'nGPUs', 2)

%% Parse input parameters
p = inputParser;
addRequired(p, 'project_path', @ischar);
addRequired(p, 'synthetic_data_path', @ischar);
addRequired(p, 'particle_radius', @isnumeric);

% Optional parameters
addParameter(p, 'dose_scale', 1.0, @isnumeric);
addParameter(p, 'link_aliStacks', false, @islogical);
addParameter(p, 'nGPUs', 1, @isnumeric);
addParameter(p, 'nCpuCores', 1, @isnumeric);
addParameter(p, 'symmetry', 'C1', @ischar);
addParameter(p, 'Cs_mm', 2.7, @isnumeric);
addParameter(p, 'voltage_kev', 300, @isnumeric);
addParameter(p, 'amplitude_contrast', 0.07, @isnumeric);

parse(p, project_path, synthetic_data_path, particle_radius, varargin{:});
opts = p.Results;

% Convert scalar particle_radius to [x,y,z] vector
if isscalar(particle_radius)
    particle_radius = [particle_radius, particle_radius, particle_radius];
end

%% Step 1: Input Validation
fprintf('=== EMC_setup_synthetic_project ===\n\n');

% Check project path does not exist
if exist(project_path, 'dir')
    error('EMC_setup_synthetic_project:ProjectExists', ...
          'Project directory already exists: %s', project_path);
end

% Check synthetic data path exists
if ~exist(synthetic_data_path, 'dir')
    error('EMC_setup_synthetic_project:DataNotFound', ...
          'Synthetic data directory not found: %s', synthetic_data_path);
end

% Find all required file types
tomosize_files = dir(fullfile(synthetic_data_path, '*.tomosize'));
csv_files = dir(fullfile(synthetic_data_path, '*.csv'));
tlt_files = dir(fullfile(synthetic_data_path, '*_ctf.tlt'));
st_files = dir(fullfile(synthetic_data_path, '*.st'));

fprintf('Found synthetic data files:\n');
fprintf('  .tomosize files: %d\n', length(tomosize_files));
fprintf('  .csv files: %d\n', length(csv_files));
fprintf('  .tlt files: %d\n', length(tlt_files));
fprintf('  .st files:  %d\n', length(st_files));

% Validate all 4 file types are present
if isempty(tomosize_files)
    error('EMC_setup_synthetic_project:MissingFiles', ...
          'No .tomosize files found in %s', synthetic_data_path);
end
if isempty(csv_files)
    error('EMC_setup_synthetic_project:MissingFiles', ...
          'No .csv files found in %s', synthetic_data_path);
end
if isempty(tlt_files)
    error('EMC_setup_synthetic_project:MissingFiles', ...
          'No *_ctf.tlt files found in %s', synthetic_data_path);
end
if isempty(st_files)
    error('EMC_setup_synthetic_project:MissingFiles', ...
          'No .st files found in %s', synthetic_data_path);
end

% For now, validate 1:1 correspondence (same count for all file types)
if length(tomosize_files) ~= length(csv_files)
    error('EMC_setup_synthetic_project:FileMismatch', ...
          'Number of .tomosize files (%d) does not match .csv files (%d)', ...
          length(tomosize_files), length(csv_files));
end
if length(tomosize_files) ~= length(tlt_files)
    error('EMC_setup_synthetic_project:FileMismatch', ...
          'Number of .tomosize files (%d) does not match .tlt files (%d)', ...
          length(tomosize_files), length(tlt_files));
end
if length(tomosize_files) ~= length(st_files)
    error('EMC_setup_synthetic_project:FileMismatch', ...
          'Number of .tomosize files (%d) does not match .st files (%d)', ...
          length(tomosize_files), length(st_files));
end

n_tomos = length(tomosize_files);
fprintf('\nProcessing %d synthetic tomogram(s)\n\n', n_tomos);

%% Step 2: Pixel Size Validation
fprintf('Validating pixel sizes...\n');

% Read pixel size from TLT file (column 16, in meters)
tlt_path = fullfile(synthetic_data_path, tlt_files(1).name);
tlt_data = load(tlt_path);
pixel_size_m = tlt_data(1, 16);  % Column 16 is pixel size in meters
pixel_size_angstrom = pixel_size_m * 1e10;

fprintf('  Pixel size from TLT: %.4f Angstroms\n', pixel_size_angstrom);

% Read and validate .tomosize files
% Format: 4 lines - x, y, z dimensions, then pixel size (Angstroms)
tomo_dimensions = zeros(n_tomos, 3);  % Store dimensions for later use
for i = 1:n_tomos
    tomosize_path = fullfile(synthetic_data_path, tomosize_files(i).name);
    fid = fopen(tomosize_path, 'r');
    if fid == -1
        error('EMC_setup_synthetic_project:FileReadError', ...
              'Could not open .tomosize file: %s', tomosize_path);
    end
    tomo_dimensions(i, 1) = str2double(fgetl(fid));  % x
    tomo_dimensions(i, 2) = str2double(fgetl(fid));  % y
    tomo_dimensions(i, 3) = str2double(fgetl(fid));  % z
    tomosize_pixel = str2double(fgetl(fid));         % pixel size
    fclose(fid);

    % Validate pixel size matches TLT
    diff_percent = abs(tomosize_pixel - pixel_size_angstrom) / pixel_size_angstrom * 100;
    if diff_percent > 1.0  % Allow 1% tolerance
        error('EMC_setup_synthetic_project:PixelSizeMismatch', ...
              'Pixel size mismatch for %s: tomosize=%.4f, TLT=%.4f Angstroms', ...
              tomosize_files(i).name, tomosize_pixel, pixel_size_angstrom);
    end
end
fprintf('  All pixel sizes validated.\n\n');

%% Step 3: Create Directory Structure
fprintf('Creating project directory structure...\n');

mkdir(project_path);
mkdir(fullfile(project_path, 'fixedStacks'));
mkdir(fullfile(project_path, 'fixedStacks', 'ctf'));
mkdir(fullfile(project_path, 'aliStacks'));
mkdir(fullfile(project_path, 'recon'));
mkdir(fullfile(project_path, 'convmap'));
mkdir(fullfile(project_path, 'cache'));
mkdir(fullfile(project_path, 'logFile'));

fprintf('  Created: %s\n', project_path);
fprintf('  Created: fixedStacks/, fixedStacks/ctf/, aliStacks/\n');
fprintf('  Created: recon/, convmap/, cache/, logFile/\n\n');

%% Process each tomogram
for i = 1:n_tomos
    % Derive tiltName from the .st filename (strip extension)
    [~, tilt_name, ~] = fileparts(st_files(i).name);

    fprintf('Processing tomogram %d: %s\n', i, tilt_name);

    %% Step 4: Process Tilt Series (.st files) - Apply Poisson noise
    st_source = fullfile(synthetic_data_path, st_files(i).name);
    st_dest_fixed = fullfile(project_path, 'fixedStacks', st_files(i).name);

    % Read the tilt series stack
    st_stack = OPEN_IMG('single', st_source);

    % Assert no negative values (required for Poisson)
    assert(all(st_stack(:) >= 0), ...
           'EMC_setup_synthetic_project:NegativeValues', ...
           'Tilt series %s contains negative values, cannot apply Poisson noise', ...
           st_files(i).name);

    % Apply Poisson noise
    st_stack = poissrnd(st_stack .* opts.dose_scale);

    % Get pixel size for saving
    mrc_obj = MRCImage(st_source, 0);
    st_header = getHeader(mrc_obj);
    st_pixel_size = st_header.cellDimensionX / st_header.nX;

    % Save noisy stack to fixedStacks/
    SAVE_IMG(st_stack, st_dest_fixed, st_pixel_size);
    fprintf('  Saved noisy .st to fixedStacks/ (dose_scale=%.2f)\n', opts.dose_scale);

    % Optionally link to aliStacks
    if opts.link_aliStacks
        st_dest_ali = fullfile(project_path, 'aliStacks', sprintf('%s_ali1.st', tilt_name));
        system(sprintf('ln -s "%s" "%s"', st_dest_fixed, st_dest_ali));
        fprintf('  Linked .st to aliStacks/\n');
    end

    %% Step 5: Link TLT Files with Correct Naming
    tlt_source = fullfile(synthetic_data_path, tlt_files(i).name);
    tlt_dest = fullfile(project_path, 'fixedStacks', 'ctf', sprintf('%s_ali1_ctf.tlt', tilt_name));

    system(sprintf('ln -s "%s" "%s"', tlt_source, tlt_dest));
    fprintf('  Linked .tlt to fixedStacks/ctf/%s_ali1_ctf.tlt\n', tilt_name);

    %% Step 5b: Generate .tlt and .xf files in fixedStacks/
    % Load the TLT data to extract angles and shifts
    tlt_full_path = fullfile(synthetic_data_path, tlt_files(i).name);
    tlt_data = load(tlt_full_path);

    % Sort by projection index (column 1) to get correct order
    tlt_sorted = sortrows(tlt_data, 1);

    % Extract tilt angles (column 4) and shifts (columns 2,3)
    tilt_angles_sorted = tlt_sorted(:, 4);
    shift_x_sorted = tlt_sorted(:, 2);
    shift_y_sorted = tlt_sorted(:, 3);

    % Write .tlt file (just tilt angles, one per line)
    tlt_angles_dest = fullfile(project_path, 'fixedStacks', sprintf('%s.tlt', tilt_name));
    fid = fopen(tlt_angles_dest, 'w');
    for j = 1:length(tilt_angles_sorted)
        fprintf(fid, '%.3f\n', tilt_angles_sorted(j));
    end
    fclose(fid);
    fprintf('  Created fixedStacks/%s.tlt\n', tilt_name);

    % Write .xf file (A11 A12 A21 A22 dX dY - identity rotation with shifts)
    xf_dest = fullfile(project_path, 'fixedStacks', sprintf('%s.xf', tilt_name));
    fid = fopen(xf_dest, 'w');
    for j = 1:length(tilt_angles_sorted)
        % Identity rotation matrix [1 0; 0 1] with shifts from TLT
        fprintf(fid, '%f %f %f %f %f %f\n', 1.0, 0.0, 0.0, 1.0, ...
                shift_x_sorted(j), shift_y_sorted(j));
    end
    fclose(fid);
    fprintf('  Created fixedStacks/%s.xf\n', tilt_name);

    %% Step 6: Convert and Create convmap CSV Files
    csv_source = fullfile(synthetic_data_path, csv_files(i).name);
    csv_data = load(csv_source);  % Load 31-column CSV

    % Extract columns 11-16: posX, posY, posZ, phi, theta, psi-phi
    if size(csv_data, 2) >= 16
        csv_6col = csv_data(:, 11:16);
    else
        error('EMC_setup_synthetic_project:InvalidCSV', ...
              'CSV file %s has only %d columns (expected at least 16)', ...
              csv_files(i).name, size(csv_data, 2));
    end

    % Write 6-column CSV to convmap/<tiltName>_1.csv
    convmap_dest = fullfile(project_path, 'convmap', sprintf('%s_1.csv', tilt_name));

    fid = fopen(convmap_dest, 'w');
    for j = 1:size(csv_6col, 1)
        fprintf(fid, '%f %f %f %f %f %f\n', csv_6col(j, :));
    end
    fclose(fid);

    fprintf('  Created convmap/%s_1.csv (%d particles)\n', tilt_name, size(csv_6col, 1));

    %% Step 7: Create recon/*.coords Files
    % Use tomogram dimensions from .tomosize file (stored earlier)
    nx = tomo_dimensions(i, 1);
    ny = tomo_dimensions(i, 2);
    nz = tomo_dimensions(i, 3);

    % Create coords file
    coords_dest = fullfile(project_path, 'recon', sprintf('%s_recon.coords', tilt_name));

    fid = fopen(coords_dest, 'w');
    fprintf(fid, '%s\n', tilt_name);  % Line 1: tiltName
    fprintf(fid, '1\n');               % Line 2: nTomos (1 for now)
    % 6 values for the tomogram: NX, NY, NZ, dX, dY, dZ
    fprintf(fid, '%d\n', nx);
    fprintf(fid, '%d\n', ny);
    fprintf(fid, '%d\n', nz);
    fprintf(fid, '0\n');               % dX (centered)
    fprintf(fid, '0\n');               % dY (centered)
    fprintf(fid, '0\n');               % dZ (centered)
    fclose(fid);

    fprintf('  Created recon/%s_recon.coords (dims: %dx%dx%d)\n', tilt_name, nx, ny, nz);
end

%% Step 8: Create Parameter File
fprintf('\nCreating parameter file...\n');

[~, project_name, ~] = fileparts(project_path);

param_path = fullfile(project_path, 'param0.m');
fid = fopen(param_path, 'w');

fprintf(fid, '%% emClarity parameter file for synthetic project: %s\n', project_name);
fprintf(fid, '%% Generated by EMC_setup_synthetic_project\n');
fprintf(fid, '%% Date: %s\n\n', datestr(now, 'yyyy-mm-dd HH:MM:SS'));

fprintf(fid, '%% Required parameters\n');
fprintf(fid, 'subTomoMeta=%s\n', project_name);
fprintf(fid, 'nGPUs=%d\n', opts.nGPUs);
fprintf(fid, 'nCpuCores=%d\n', opts.nCpuCores);
fprintf(fid, 'symmetry=%s\n', opts.symmetry);
fprintf(fid, 'PIXEL_SIZE=%.6e\n', pixel_size_m);
fprintf(fid, 'Cs=%.6e\n', opts.Cs_mm * 1e-3);
fprintf(fid, 'VOLTAGE=%.6e\n', opts.voltage_kev * 1e3);
fprintf(fid, 'AMPCONT=%.4f\n\n', opts.amplitude_contrast);

fprintf(fid, '%% Particle parameters\n');
fprintf(fid, 'particleRadius=[%d,%d,%d]\n\n', ...
        particle_radius(1), particle_radius(2), particle_radius(3));

fprintf(fid, '%% Sampling rates\n');
fprintf(fid, 'Ali_samplingRate=1\n');
fprintf(fid, 'Cls_samplingRate=1\n');
fprintf(fid, 'Tmp_samplingRate=1\n\n');

fprintf(fid, '%% Classification defaults\n');
fprintf(fid, 'flgClassify=0\n');
fprintf(fid, 'Pca_clusters=2\n');

fclose(fid);

fprintf('  Created param0.m\n');

%% Step 9: Validation Summary
fprintf('\n=== Project Setup Complete ===\n\n');
fprintf('Project directory: %s\n', project_path);
fprintf('Tomograms processed: %d\n', n_tomos);
fprintf('Pixel size: %.4f Angstroms\n', pixel_size_angstrom);
fprintf('Particle radius: [%d, %d, %d] Angstroms\n', ...
        particle_radius(1), particle_radius(2), particle_radius(3));
fprintf('\nNext step: cd to project directory and run:\n');
fprintf('  emClarity init param0.m zyz fwd\n\n');

end  % main function
