"""Membrane-geometry constraint (DESIGN §7; SPEC §8).

True membrane-associated targets sit within a thin shell around the membrane on the correct
side (template ``+Z`` outward). This constraint penalizes two false-positive geometries:

* **wrong-side membrane-lattice hits** — a candidate that lies on the membrane but faces the
  wrong way (the membrane's periodic lattice throws off-side ghosts);
* **small closed interior vesicles** — the extended outer mito membrane is low-curvature, while
  interior replication vesicles are small closed shells with a large signed-distance Laplacian
  (``closed_shell``); a hit inside such a vesicle is a false positive.

The membrane field is generated by a provider (SPEC §8 — none exists on disk today), so when the
membrane features are MISSING (or NaN per candidate) the constraint is neutral for those
candidates, per the DESIGN §5 mixed-availability rule.
"""

from __future__ import annotations

from typing import Dict, Optional

import numpy as np
from numpy.typing import NDArray

from ..features.extractor import FeatureMatrix
from .base import ParamDict, ParamSpec
from .combine import (
    _BaseConstraint,
    finite_mask,
    get_feature,
    register_constraint,
    sigmoid,
    soft_or,
)

_DIST_ALIASES = ("membrane_dist", "membrane_dist_A")
_SIDE_ALIASES = ("inside_sign",)
_CLOSED_ALIASES = ("closed_shell",)
_FACING_ALIASES = ("membrane_facing",)


@register_constraint("membrane_geometry")
class MembraneGeometryConstraint(_BaseConstraint):
    """Penalize wrong-side membrane hits and small closed interior vesicles (SPEC §8).

    The wrong-side term fires only for candidates *on* the membrane (``|dist| < shell``) whose
    ``inside_sign`` is the false-positive side (``fp_side``, default inside ``-1``). The vesicle
    term is a sigmoid on the closed-shell curvature magnitude, separating small high-curvature
    interior vesicles from the extended low-curvature outer membrane. The two are soft-OR'd.

    Args:
        shell_A: Membrane shell half-width (Angstrom); ``|dist|`` inside it counts as on-membrane.
        dist_sharpness: Steepness of the on-membrane sigmoid (per Angstrom).
        wrong_side_weight: Weight of the wrong-side penalty (``0..1``).
        fp_side: Which ``inside_sign`` is the false-positive side (``-1`` inside, ``+1`` outside).
        closed_thresh: Closed-shell curvature (``1/Angstrom``) above which a vesicle penalizes.
        closed_sharpness: Steepness of the vesicle sigmoid (per ``1/Angstrom``).
        vesicle_weight: Weight of the vesicle penalty (``0..1``).
        misface_thresh: Facing cosine (template ``+Z`` vs membrane outward normal) below which an
            on-membrane hit is penalized as wrong-side / interior (``-1..1``).
        misface_sharpness: Steepness of the mis-facing sigmoid (per unit cosine).
        misface_weight: Weight of the mis-facing penalty (``0..1``; ``0`` = off until tuned).
    """

    name = "membrane_geometry"
    needs_features = ("membrane_dist", "inside_sign", "closed_shell", "membrane_facing")
    param_schema: Dict[str, ParamSpec] = {
        "shell_A": ParamSpec(0.0, 300.0, 80.0),
        "dist_sharpness": ParamSpec(1.0e-3, 0.5, 0.05, log=True),
        "wrong_side_weight": ParamSpec(0.0, 1.0, 0.5),
        "closed_thresh": ParamSpec(0.0, 0.05, 0.01),
        "closed_sharpness": ParamSpec(1.0, 2000.0, 200.0, log=True),
        "vesicle_weight": ParamSpec(0.0, 1.0, 1.0),
        "misface_thresh": ParamSpec(-1.0, 1.0, 0.7),
        "misface_sharpness": ParamSpec(0.5, 20.0, 5.0, log=True),
        "misface_weight": ParamSpec(0.0, 1.0, 0.5),
    }

    def __init__(
        self,
        shell_A: float = 80.0,
        dist_sharpness: float = 0.05,
        wrong_side_weight: float = 0.5,
        fp_side: float = -1.0,
        closed_thresh: float = 0.01,
        closed_sharpness: float = 200.0,
        vesicle_weight: float = 1.0,
        misface_thresh: float = 0.7,
        misface_sharpness: float = 5.0,
        misface_weight: float = 0.0,
        **params: object,
    ) -> None:
        super().__init__(
            shell_A=shell_A,
            dist_sharpness=dist_sharpness,
            wrong_side_weight=wrong_side_weight,
            fp_side=fp_side,
            closed_thresh=closed_thresh,
            closed_sharpness=closed_sharpness,
            vesicle_weight=vesicle_weight,
            misface_thresh=misface_thresh,
            misface_sharpness=misface_sharpness,
            misface_weight=misface_weight,
            **params,
        )
        self.fp_side = float(fp_side)

    def forward(self, feats: FeatureMatrix, theta: ParamDict) -> NDArray[np.float32]:
        """Return the per-candidate membrane-geometry false-positive score in ``[0, 1]``.

        Args:
            feats: The per-candidate feature matrix.
            theta: The resolved tunable parameter values.

        Returns:
            A ``(N,)`` false-positive score; all zeros for candidates whose membrane features are
            absent or NaN.
        """
        n = feats.n
        p = self.resolved(theta)
        terms: list[NDArray[np.float64]] = []

        # On-membrane gate (shared by the wrong-side and mis-facing terms).
        dist: Optional[NDArray[np.float64]] = get_feature(feats, _DIST_ALIASES)
        on_membrane: Optional[NDArray[np.float64]] = None
        dist_valid: Optional[NDArray[np.bool_]] = None
        if dist is not None:
            dist_valid = finite_mask(dist)
            d = np.where(dist_valid, dist, 0.0)
            on_membrane = sigmoid(p["dist_sharpness"] * (p["shell_A"] - np.abs(d)))

        side: Optional[NDArray[np.float64]] = get_feature(feats, _SIDE_ALIASES)
        if on_membrane is not None and side is not None and dist_valid is not None:
            valid = dist_valid & finite_mask(side)
            s = np.where(valid, side, 0.0)
            wrong = 0.5 * (1.0 + self.fp_side * s)  # 1 when s == fp_side, 0 on the correct side
            term_side = np.where(valid, on_membrane * wrong, 0.0) * p["wrong_side_weight"]
            terms.append(term_side)

        # Mis-facing: a membrane hit whose template +Z disagrees with the local membrane outward
        # normal (wrong-side lattice ghost / interior vesicle) faces the WRONG way (low cosine).
        facing: Optional[NDArray[np.float64]] = get_feature(feats, _FACING_ALIASES)
        if facing is not None:
            valid_f = finite_mask(facing)
            f = np.where(valid_f, facing, 1.0)  # missing facing -> treat as aligned (no penalty)
            gate = on_membrane if on_membrane is not None else np.ones(n, dtype=np.float64)
            misface = sigmoid(p["misface_sharpness"] * (p["misface_thresh"] - f))
            term_face = np.where(valid_f, gate * misface, 0.0) * p["misface_weight"]
            terms.append(term_face)

        closed: Optional[NDArray[np.float64]] = get_feature(feats, _CLOSED_ALIASES)
        if closed is not None:
            valid_c = finite_mask(closed)
            c = np.where(valid_c, closed, 0.0)
            ves = sigmoid(p["closed_sharpness"] * (c - p["closed_thresh"]))
            term_ves = np.where(valid_c, ves, 0.0) * p["vesicle_weight"]
            terms.append(term_ves)

        return np.asarray(soft_or(terms, n), dtype=np.float32)
